### ISSUE TITLE
No publishable resources for tag [].  

### ISSUE THREAD

**Issue by ijpatricio** [protonemedia/laravel-task-runner#1]
Hey @pascalbaljet sounds real interesting, thought of giving it a spin!

Running `php artisan vendor:publish --provider="\ProtoneMedia\LaravelTaskRunner\ServiceProvider"`

```
   INFO  No publishable resources for tag [].  
```

I tried to find a solution to make PR as it seemed simpler, but I don't know my way around the "Spatie Packager Wrapper".

Let me know over a comment if you have any idea, I'll gladly do the PR

**Comment by pascalbaljet** [comment]
Ahh whoops, it's without the leading backslash:

```bash
php artisan vendor:publish --provider="ProtoneMedia\LaravelTaskRunner\ServiceProvider"
```

I'll update the README, thanks for the heads up!
